[package]
name = "librarian"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
env_logger = "0.11.7"
infer = "0.19.0"
log = "0.4.27"
memchr = "2.7.4"
rayon = "1.10.0"
walkdir = "2.5.0"
